### ISSUE TITLE
Cannot use in IDEA 13

### ISSUE THREAD

**Issue by reinert** [ArcBees/gwtp-idea-plugin#44]
The plugin is failing even in simple use cases as the presenter creation example (http://www.youtube.com/watch?v=_u03xsCYpS0&feature=youtu.be) in IDEA 13.

**Comment by branflake2267** [comment]
Could you provide a test case to replicate the issue? A test case would be a zipped up project that replicates the issue.

**Comment by reinert** [comment]
Now, I've tried to create a new project and it worked.

I went back to my project and found two reasons for the error:
1) I use NameTokens and ClientModule classes at client package. (It would
be nice if we could set these two locations)
2) I use RoutePlace NameTokens.

When I modified these two following GWTP's pattern, then the plugin worked.

## 

D. Reinert

On Mon, Dec 23, 2013 at 1:25 PM, Brandon Donnelson <notifications@github.com

**Comment by branflake2267** [comment]
Great idea, I should have it find the module on open, and allow for location change instead of doing that in processing. Same for both locations.

**Comment by branflake2267** [comment]
https://github.com/ArcBees/gwtp-idea-plugin/issues/45 > created
