### ISSUE TITLE
Importing maven org.jetbrains.idea.maven

### ISSUE THREAD

**Issue by sajithdilshan** [ArcBees/gwtp-idea-plugin#46]
I've cloned this repo and tried to build it. but Idea is unable to import maven org.jetbrains.idea.maven related classes. I'm using IDEA 13 as SDK.

**Comment by olafleur** [comment]
Did you download the source code of IDEA? You need it to make the plugin work

**Comment by branflake2267** [comment]
That doesn't make sense to me, build it? There is not building as far as I know. Import the source and setup the SDK. Although I have to admit I haven't worked with the plugin in IDEA 13 yet, but should be the same as 12.

**Comment by branflake2267** [comment]
I think I'm thinking build in maven context. How is the module settings configured? 

What I do is setup a brand new plugin and then compare module settings configuration, are they the same.

**Comment by sajithdilshan** [comment]
I had to add the maven.jar from {IDEAdirectory}/plugins/maven as a library to the plugin inside IDEA. After that it resolved all the imports

**Comment by branflake2267** [comment]
Nice job
