### ISSUE TITLE
Plugin is not working in IntelliJ 14.

### ISSUE THREAD

**Issue by arkadyes** [ArcBees/gwtp-idea-plugin#55]
Hi,

I just installed the GWTP plugin in IntelliJ 14.0.3 but it is not working. When IntelliJ starts I see the following exception in the Event Log:

PluginException: cannot create class "com.arcbees.plugin.idea.wizards.createpresenter.CreatePresenterAction" [Plugin: com.arcbees.plugin.idea]

When I click the File -> New Project menu item I see the following exception:

PluginException: com/arcbees/plugin/idea/moduletypes/CreateProjectModuleType : Unsupported major.minor version 51.0 [Plugin: com.arcbees.plugin.idea]

Best regards,

Arkady.

**Comment by arkadyes** [comment]
Sorry, I didn't see the closed issue #54.

**Comment by meriouma** [comment]
The new version was compiled using Java 7. I've just uploaded a new version compiled with Java 6, it should be available soon. Please note that Java 6 support will be remove at some point
