### ISSUE TITLE
Creating new GWTP project fails

### ISSUE THREAD

**Issue by arkadyes** [ArcBees/gwtp-idea-plugin#58]
Hi,

I am trying to create a GWTP project in IntelliJ but getting the following error:

"IllegalStateException: Maven application directory was not specified, and ${maven.home} is not provided in the system properties. Please specify at least on of these."

I have maven installed and added to the PATH. I also have M2_HOME defined.

What am I missing?

Thanks.

Best regards,

Arkady.

**Comment by spg** [comment]
Have you tried setting, in InteliJ:  Preferences > Build, Execution, Deployment > Build Tools > Maven > Maven home directory ?

**Comment by arkadyes** [comment]
It says that it is using M2_HOME by default. So I defined M2_HOME.

**Comment by spg** [comment]
What OS are you using?

**Comment by arkadyes** [comment]
Mac OS X 10.9.5

**Comment by arkadyes** [comment]
Any suggestions?

**Comment by arkadyes** [comment]
So I don't see any response for the last 10 days. Is MAC OS X not supported? Or how do I make it work?

Thanks.

**Comment by meriouma** [comment]
Do you have the same error with the latest version? It's hard for me to reproduce the issue as I'm on Windows

**Comment by arkadyes** [comment]
I am on IntelliJ 14.0.3. What latest version are you talking about?

**Comment by meriouma** [comment]
Version of the plugin, latest is 1.2.0-beta3.

**Comment by arkadyes** [comment]
Yes, the same error happens with plugin version 1.2.0-beta3.

**Comment by Pacane** [comment]
How have you defined your m2_home (in which file)? can you `echo $M2_HOME` and show us the result? Is the result the same from IntelliJ integrated terminal vs your system's terminal?

Also are you using a custom terminal emulator? Do you use bash? zsh?

**Comment by spg** [comment]
Have you tried this? http://stackoverflow.com/questions/7053666/maven-home-m2-home-not-being-picked-up-by-intellij-idea

**Comment by arkadyes** [comment]
The M2_HOME is defined in ~/.bash_profile file.

arkady-mbp:~ arkady$ echo $M2_HOME
/Users/arkady/dev/apache-maven-3.2.5

The result is the same from system terminal and IntelliJ integrated terminal.

**Comment by arkadyes** [comment]
Following the instructions in the  http://stackoverflow.com/questions/7053666/maven-home-m2-home-not-being-picked-up-by-intellij-idea solved the issue.

Thanks a lot.
