### ISSUE TITLE
Incorrect Presenter package location in multi-module projects

### ISSUE THREAD

**Issue by clayharris** [ArcBees/gwtp-idea-plugin#59]
I just switched to IntelliJ, and I'm running across an issue with the GWTP plugin (v 1.2.0-beta3).

My project has multiple semi-interrelated modules within it.  There is a parent pom in the root directory, and each module has its own pom.xml referencing the parent.  Most of the modules are GWTP based.

When using the plugin, I select the package I want the new presenter in, right click, new -> GWTP -> Create a GWTP Presenter With View.  The package is set correctly, and install(new module) is added in the correct location, but the generated presenter /view etc files are all placed in a completely separate and unrelated module.  I then have to move the files to the correct location.  

It's not even consistent as to where it places it - a coworker had it place the files in one module, and for me it places them a different one - never the correct one however heh.

**Comment by BenDol** [comment]
Having this same issue, needs a module selection mechanism.

**Comment by olafleur** [comment]
We juste released version 1.2.0 of the plugin.
Could you confirm that you still have this problem?

**Comment by BenDol** [comment]
I am using 1.2.0

**Comment by BenDol** [comment]
Not sure if we can cherry pick my latest commit, since all that code is the same as this 1.2.0 branch, I only removed maven from the project so I could hotswap and debug the plugin issues. (Wasn't sure how to do it with the strange maven implementation).

**Comment by BenDol** [comment]
Well I committed half of this fix in the removal on maven commit so just check the ContentSlotDialog.java code for its resolve: https://github.com/BenDol/gwtp-idea-plugin/blob/8c7c70e43a69f33488bfe20185680f235753c2f1/src/main/com/arcbees/plugin/idea/dialogs/ContentSlotDialog.java

**Comment by BenDol** [comment]
@Lanik42 if you pull my fork of the plugin and open it with intellij you should be able to do a `Build -> Prepare All Plugin Modules for Deploy` then reinstall the gwtp plugin with the produced jar file. Then test to ensure it has resolved the issue for you.
