### ISSUE TITLE
Doesn't support new NestedSlot content slot

### ISSUE THREAD

**Issue by BenDol** [ArcBees/gwtp-idea-plugin#74]

**Comment by olafleur** [comment]
Could you clarify what you mean? Here when I use the last version of the IntelliJ plugin (1.2.0) I am able to create a NestedSlot without a problem.

**Comment by BenDol** [comment]
It doesn't detect my NestedSlot's (in 1.2.0 branch):

``` java
public static final NestedSlot SLOT_CONTENT = new NestedSlot();

public static final NestedSlot SLOT_LOADING = new NestedSlot();

public static final NestedSlot SLOT_INFO = new NestedSlot();
```

I've patched a version on my local fork repository along with a fix for https://github.com/ArcBees/gwtp-idea-plugin/issues/59 will commit it soon and link it. Can't make a PR because I couldn't figure out how to run the intellij plugin in debug mode with the maven setup (there aren't very clear instructions on how to manage it in maven unfortunately). So I converted this project to not require maven, since it doesn't really need to use maven IMO :D

**Comment by olafleur** [comment]
Not sure what you mean by not detecting.

To run the IntelliJ plugin, you install it via the Plugins menu of IntelliJ and after that you have the option to create a project or a presenter/view pair in a contextual menu.

**Comment by BenDol** [comment]
This is what I was getting before:
![issue](https://cloud.githubusercontent.com/assets/1935706/9764401/119c4a20-5763-11e5-8509-30ed4b3c204b.png)
